In [272]:
# import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn import ensemble
import joblib
import sklearn

In [275]:
import pandas as pd
import numpy as np
from collections import Counter
pd.set_option('display.max_columns', None)

from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [304]:
total = pd.read_csv('./train_features.csv')
total

year  month  day  hour  weekday  is_weekend  is_holiday  free  \
0         0      1    1     0        6           1           0   1.0   
1         0      1    1     1        6           1           0   1.0   
2         0      1    1     2        6           1           0   1.0   
3         0      1    1     3        6           1           0   1.0   
4         0      1    1     4        6           1           0   1.0   
...     ...    ...  ...   ...      ...         ...         ...   ...   
14001     1     12   31    12        0           0           0   0.0   
14002     1     12   31    15        0           0           0   0.0   
14003     1     12   31    16        0           0           0   0.0   
14004     1     12   31    18        0           0           0   0.0   
14005     1     12   31    20        0           0           0   0.0   

       maxtempC  mintempC  totalSnow_cm  sunHour  uvIndex  moon_illumination  \
0            21        17           0.0      8.7        5                 20   
1            21        17           0.0      8.7        5                 20   
2            21        17           0.0      8.7        5                 20   
3            21        17           0.0      8.7        5                 20   
4            21        17           0.0      8.7        5                 20   
...         ...       ...           ...      ...      ...                ...   
14001        12        11           0.0      3.9        3                 36   
14002        12        11           0.0      3.9        3                 36   
14003        12        11           0.0      3.9        3                 36   
14004        12        11           0.0      3.9        3                 36   
14005        12        11           0.0      3.9        3                 36   

       moonrise  moonset  sunrise  sunset  DewPointC  FeelsLikeC  HeatIndexC  \
0             9       20        7      17         15          19          20   
1             9       20        7      17         15          19          20   
2             9       20        7      17         15          19          20   
3             9       20        7      17         15          19          20   
4             9       20        7      17         15          19          20   
...         ...      ...      ...     ...        ...         ...         ...   
14001         1       13        7      17          6          10          12   
14002         1       13        7      17          6          10          12   
14003         1       13        7      17          6          10          12   
14004         1       13        7      17          6          10          12   
14005         1       13        7      17          6          10          12   

       WindChillC  WindGustKmph  cloudcover  humidity  precipMM  pressure  \
0              19            23          30        80       0.0      1021   
1              19            23          30        80       0.0      1021   
2              19            23          30        80       0.0      1021   
3              19            23          30        80       0.0      1021   
4              19            23          30        80       0.0      1021   
...           ...           ...         ...       ...       ...       ...   
14001          10            21          79        69       0.0      1028   
14002          10            21          79        69       0.0      1028   
14003          10            21          79        69       0.0      1028   
14004          10            21          79        69       0.0      1028   
14005          10            21          79        69       0.0      1028   

       tempC  visibility  winddirDegree  windspeedKmph      speed  
0         21          10             76             16  43.002930  
1         21          10             76             16  46.118696  
2         21          10             76             16  44.294158  
3         21          1

In [305]:
features = total.drop('speed', axis=1)
labels = total['speed']

In [289]:
# features

In [290]:
# labels

In [291]:
# train_x = total.drop(['year', 'speed'], axis=1)[:8750]
# train_y = total['speed'][:8750]

# test_x = total.drop(['year', 'speed'], axis=1)[8750:] 
# test_y = total['speed'][8750:]

In [292]:
# train_x

In [293]:
# train = train.sample(frac=1)

# train_x = train.drop('speed', axis=1)
# train_y = train['speed']

# test_x = test.drop('speed', axis=1)
# test_y = test['speed']

In [239]:
# train_x = features
# train_y = labels

In [297]:
# from sklearn.model_selection import train_test_split
# train_x, test_x, train_y, test_y = train_test_split(features, labels, test_size=0.3, random_state=27)

In [294]:
# to_scale = ['pressure', 'winddirDegree', 'humidity', 'cloudcover']
# train_xToScale = train_x[to_scale]
# train_x = train_x.drop(to_scale, axis=1)

# testToScale = test_x[to_scale]
# test_x = test_x.drop(to_scale, axis=1)

# train_yToScale = train_y.to_numpy().reshape(-1, 1)

# featuresToScale = features[to_scale]
# features = features.drop(to_scale, axis=1)

# labelToScale = label.to_numpy().reshape(-1, 1)

In [298]:
# scaler_features = StandardScaler()
# scaler_features.fit(train_xToScale)
# train_xScaled = scaler_features.transform(train_xToScale)
# test_xScaled = scaler_features.transform(testToScale)

# scaler_label = StandardScaler()
# scaler_label.fit(train_yToScale)
# train_y = scaler_label.transform(train_yToScale)

# scaler_features = StandardScaler()
# scaler_features.fit(featuresToScale)
# featuresScaled = scaler_features.transform(featuresToScale)

# scaler_label = StandardScaler()
# scaler_label.fit(labelToScale)
# labelScaled = scaler_label.transform(labelToScale)

In [282]:
# train_x = np.concatenate([train_x, train_xScaled], axis=1)
# test_x = np.concatenate([test_x, test_xScaled], axis=1)

# features = np.concatenate([features, featuresScaled], axis=1)

In [283]:
train_y = train_y.ravel()
test_y = test_y.ravel()

# labels = labels.to_numpy().ravel()

# Random Forest

In [306]:
train_x = features.to_numpy()
# train_y = train_y.ravel()
train_y = labels.to_numpy().ravel()

# test_x = test_x.to_numpy()
# test_y = test_y.to_numpy().ravel()

In [307]:
print(train_x.shape)
print(train_y.shape)

# print(test_x.shape)
# print(test_y.shape)

(14006, 31)
(14006,)


In [197]:
model_rf = ensemble.RandomForestRegressor()

model_rf.fit(train_x, train_y)

# joblib.dump(model_rf, './models/RandomForest.rf')

RandomForestRegressor()

In [198]:
# model_rf = joblib.load('./models/RandomForest.rf')
result = model_rf.predict(test_x)
result = result.reshape(-1, 1)
test_y = test_y.reshape(-1, 1)

result = scaler_label.inverse_transform(result)

mse = mean_squared_error(test_y, result)
print('MSE: ' + str(mse))

MSE: 0.0021646999159993944


# XGBoost

In [308]:
from xgboost import XGBRegressor
# from xgboost import XGBRFRegressor
model_xgb = XGBRegressor(learning_rate=0.1, n_estimators=250, max_depth=8, min_child_weight=1, gamma=0,
                            objective='reg:squarederror', subsample=1, reg_lambda=0.8, eval_metric='rmse')

model_xgb.fit(train_x, train_y)

# joblib.dump(model_xgb, './models/XGBoost.xg')

XGBRegressor(eval_metric='rmse', max_depth=8, n_estimators=250,
             objective='reg:squarederror', reg_lambda=0.8)

In [303]:
# model_rf = joblib.load('./models/RandomForest.rf')
result = model_xgb.predict(test_x)
# result = result.reshape(-1, 1)
# test_y = test_y.reshape(-1, 1)

# result = scaler_label.inverse_transform(result)

mse = mean_squared_error(test_y, result)
print('MSE: ' + str(mse))

MSE: 11.273526791916096


In [248]:
result

array([[43.69653 ],
       [47.650627],
       [50.625214],
       ...,
       [12.498634],
       [16.014389],
       [40.60627 ]], dtype=float32)

In [362]:
model_xgb.feature_importances_

array([0.00031611, 0.00153928, 0.00137027, 0.03025433, 0.00027342,
       0.00041797, 0.00040786, 0.00186808, 0.00030101, 0.00137152,
       0.00058433, 0.07677506, 0.07390901, 0.09610714, 0.08459601,
       0.09887618, 0.05910677, 0.0670846 , 0.00236918, 0.03972499,
       0.02439893, 0.00148158, 0.00295119, 0.01534161, 0.01654601,
       0.03078699, 0.01798806, 0.02255179, 0.04303231, 0.07596528,
       0.0028357 , 0.01248473, 0.03654223, 0.01253346, 0.02299124,
       0.00040224, 0.0002817 , 0.00030365, 0.00036981, 0.00076365,
       0.00338753, 0.01650518, 0.00045959, 0.00048834, 0.00045223,
       0.00043901, 0.0004629 ], dtype=float32)

# Test

In [309]:
test_x = pd.read_csv('./test_features.csv')
test_x

year  month  day  hour  weekday  is_weekend  is_holiday  free  maxtempC  \
0        1      1    1     2        0           0           1   1.0        19   
1        1      1    1     5        0           0           1   1.0        19   
2        1      1    1     7        0           0           1   1.0        19   
3        1      1    1     8        0           0           1   1.0        19   
4        1      1    1    10        0           0           1   1.0        19   
...    ...    ...  ...   ...      ...         ...         ...   ...       ...   
3499     1     12   31    17        0           0           0   0.0        12   
3500     1     12   31    19        0           0           0   0.0        12   
3501     1     12   31    21        0           0           0   0.0        12   
3502     1     12   31    22        0           0           0   0.0        12   
3503     1     12   31    23        0           0           0   0.0        12   

      mintempC  totalSnow_cm  sunHour  uvIndex  moon_illumination  moonrise  \
0           16           0.0      8.7        5                 97        17   
1           16           0.0      8.7        5                 97        17   
2           16           0.0      8.7        5                 97        17   
3           16           0.0      8.7        5                 97        17   
4           16           0.0      8.7        5                 97        17   
...        ...           ...      ...      ...                ...       ...   
3499        11           0.0      3.9        3                 36         1   
3500        11           0.0      3.9        3                 36         1   
3501        11           0.0      3.9        3                 36         1   
3502        11           0.0      3.9        3                 36         1   
3503        11           0.0      3.9        3                 36         1   

      moonset  sunrise  sunset  DewPointC  FeelsLikeC  HeatIndexC  WindChillC  \
0           5        7      17         11          18          18          18   
1           5        7      17         11          18          18          18   
2           5        7      17         11          18          18          18   
3           5        7      17         11          18          18          18   
4           5        7      17         11          18          18          18   
...       ...      ...     ...        ...         ...         ...         ...   
3499       13        7      17          6          10          12          10   
3500       13        7      17          6          10          12          10   
3501       13        7      17          6          10          12          10   
3502       13        7      17          6          10          12          10   
3503       13        7      17          6          10          12          10   

      WindGustKmph  cloudcover  humidity  precipMM  pressure  tempC  \
0               14          23        63       0.0      1020     19   
1               14          23        63       0.0      1020     19   
2               14          23        63       0.0      1020     19   
3               14          23        63       0.0      1020     19   
4               14          23        63       0.0      1020     19   
...            ...         ...       ...       ...       ...    ...   
3499            21          79        69       0.0      1028     12   
3500            21          79        69       0.0      1028     12   
3501            21          79        69       0.0      1028     12   
3502            21          79        69       0.0      1028     12   
3503            21          79        69       0.0      1028     12   

      visibility  winddirDegree  windspeedKmph  
0             10             65             12  
1             10             65             12  
2             10             65             12  
3             10             65             12  
4            

In [257]:
# test_xToScale = test_x[to_scale]
# test_x = test_x.drop(to_scale, axis=1)

# test_xScaled = scaler_features.transform(test_xToScale)

# test_x = np.concatenate([test_x, test_xScaled], axis=1)

In [310]:
test_x.shape

(3504, 31)

In [311]:
# model_xgb = joblib.load('./models/XGBoost.xg')
test_x = test_x.to_numpy()
result = model_xgb.predict(test_x)

In [312]:
result

array([48.05364 , 47.86248 , 39.170265, ..., 48.490707, 40.54639 ,
       41.366497], dtype=float32)

In [206]:
# result = scaler_label.inverse_transform(result)

In [313]:
final = pd.DataFrame({'id':range(len(result)), 'speed':result})
final

id      speed
0        0  48.053638
1        1  47.862480
2        2  39.170265
3        3  31.181509
4        4  38.886971
...    ...        ...
3499  3499  11.436890
3500  3500  23.810772
3501  3501  48.490707
3502  3502  40.546391
3503  3503  41.366497

[3504 rows x 2 columns]

In [314]:
final.to_csv('./test_result.csv', encoding='utf-8', index=False)